name: yummy_lingo
description: Yummy Lingo

version: 1.2.10+54

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audio_service: ^0.18.0
  audio_session: ^0.1.3
  auto_route: ^4.0.1
  cached_network_image: ^3.0.0
  cloud_firestore: ^3.1.0
  connectivity: ^3.0.6
  dartz: ^0.10.0
  dio: ^4.0.0
  firebase_analytics: ^9.0.1
  firebase_auth: ^3.0.0
  flutter_cache_manager: ^3.1.3
  firebase_crashlytics: ^2.0.6
  firebase_remote_config: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.0
  freezed_annotation: ^2.0.1
  get_it: ^7.1.3
  google_sign_in: ^5.0.4
  in_app_purchase: ^3.0.0
  injectable: ^1.5.0
  intl: ^0.17.0
  just_audio: ^0.9.1
  material_design_icons_flutter: ^5.0.6595
  moor_flutter: ^4.0.0
  path_provider: ^2.0.2
  percent_indicator: ^4.0.0
  permission_handler: ^9.0.1
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^4.0.0
  url_launcher: ^6.0.6
  uuid: ^3.0.4
  wakelock: ^0.6.0+1

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.1
  fast_i18n: ^5.9.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.0.0
  freezed: ^2.0.2
  injectable_generator: ^1.4.1
  lint: ^1.5.3
  moor_generator: ^4.3.1

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/splash.png
  color: "#1287a8"

flutter:
  uses-material-design: true
  fonts:
    - family: PT Sans
      fonts:
        - asset: assets/fonts/pt_sans/PTSans-Regular.ttf
        - asset: assets/fonts/pt_sans/PTSans-Italic.ttf
        - asset: assets/fonts/pt_sans/PTSans-Bold.ttf
        - asset: assets/fonts/pt_sans/PTSans-BoldItalic.ttf
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/roboto_condensed/RobotoCondensed-Bold.ttf
    - family: Roboto Slab
      fonts:
        - asset: assets/fonts/roboto_slab/RobotoSlab-Black.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-Bold.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-ExtraBold.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-ExtraLight.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-Light.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-Medium.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-Regular.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-SemiBold.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-Thin.ttf

  assets:
    - assets/images/
    - assets/fonts/
